import { useState } from "react";
import { ArrowRight, Sparkles, Github } from "lucide-react";

export function Hero() {
  const [url, setUrl] = useState("https://github.com/langchain-ai/langchain");
  return (
    <section id="top" className="relative overflow-hidden bg-hero">
      <div className="absolute inset-0 bg-grid pointer-events-none" />
      <div className="absolute -top-32 left-1/2 -translate-x-1/2 h-[500px] w-[800px] rounded-full bg-primary/10 blur-3xl pointer-events-none" />

      <div className="relative mx-auto max-w-7xl px-6 pt-20 pb-28 md:pt-28 md:pb-36">
        <div className="mx-auto max-w-3xl text-center">
          <div className="inline-flex items-center gap-2 rounded-full border border-border bg-card/60 px-3 py-1 text-xs text-muted-foreground backdrop-blur">
            <Sparkles className="h-3 w-3 text-primary" />
            Powered by Gemini · LangChain · LangGraph
          </div>

          <h1 className="mt-6 text-4xl md:text-6xl lg:text-7xl font-bold leading-[1.05] tracking-tight">
            Understand any <span className="text-gradient">GitHub repo</span>
            <br />
            in seconds.
          </h1>

          <p className="mt-6 text-base md:text-lg text-muted-foreground max-w-2xl mx-auto">
            Paste a repository URL. Get a full project breakdown, tailored interview questions, and
            a clean step-by-step setup guide — generated by an AI agent that actually reads the
            code.
          </p>

          <form
            onSubmit={(e) => {
              e.preventDefault();
              document.getElementById("demo")?.scrollIntoView({ behavior: "smooth" });
            }}
            className="mt-10 mx-auto flex max-w-2xl items-center gap-2 rounded-xl border border-border bg-card/80 p-1.5 shadow-card backdrop-blur"
          >
            <div className="pl-3 text-muted-foreground">
              <Github className="h-4 w-4" />
            </div>
            <input
              value={url}
              onChange={(e) => setUrl(e.target.value)}
              placeholder="https://github.com/owner/repo"
              className="flex-1 bg-transparent px-2 py-2.5 text-sm font-mono outline-none placeholder:text-muted-foreground/60"
            />
            <button
              type="submit"
              className="inline-flex items-center gap-1.5 rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground hover:opacity-90 transition shadow-glow"
            >
              Analyze <ArrowRight className="h-4 w-4" />
            </button>
          </form>

          <div className="mt-6 flex items-center justify-center gap-6 text-xs text-muted-foreground">
            <span className="flex items-center gap-1.5">
              <span className="h-1.5 w-1.5 rounded-full bg-primary animate-pulse-dot" /> No signup
              required
            </span>
            <span className="hidden sm:flex items-center gap-1.5">
              <span className="h-1.5 w-1.5 rounded-full bg-accent animate-pulse-dot" /> Works with
              private API key
            </span>
            <span className="hidden sm:flex items-center gap-1.5">
              <span className="h-1.5 w-1.5 rounded-full bg-amber animate-pulse-dot" /> Open source
            </span>
          </div>
        </div>

        {/* Floating preview card */}
        <div className="relative mt-20 mx-auto max-w-5xl">
          <div className="absolute -inset-x-10 -top-10 h-40 bg-primary/10 blur-3xl rounded-full" />
          <div className="relative rounded-2xl border border-border bg-card/80 backdrop-blur shadow-card overflow-hidden animate-float">
            <div className="flex items-center gap-2 border-b border-border px-4 py-3 bg-background/40">
              <div className="flex gap-1.5">
                <span className="h-3 w-3 rounded-full bg-destructive/70" />
                <span className="h-3 w-3 rounded-full bg-amber/70" />
                <span className="h-3 w-3 rounded-full bg-primary/70" />
              </div>
              <div className="ml-3 font-mono text-xs text-muted-foreground">
                POST /api/v1/analyze
              </div>
              <div className="ml-auto flex items-center gap-1.5 text-xs font-mono text-primary">
                <span className="h-1.5 w-1.5 rounded-full bg-primary animate-pulse-dot" /> 200 OK
              </div>
            </div>
            <div className="grid md:grid-cols-2 divide-y md:divide-y-0 md:divide-x divide-border">
              <pre className="p-5 text-xs font-mono leading-relaxed overflow-x-auto text-muted-foreground">
                {`{
  "github_url": "github.com/langchain-ai/langchain",
  "difficulty": "intermediate",
  "num_questions": 10
}`}
              </pre>
              <div className="p-5 text-xs font-mono leading-relaxed space-y-3">
                <div>
                  <span className="text-primary">▸ project_name</span>{" "}
                  <span className="text-foreground">LangChain</span>
                </div>
                <div>
                  <span className="text-primary">▸ tech_stack</span>{" "}
                  <span className="text-foreground">Python · LCEL · Pydantic</span>
                </div>
                <div>
                  <span className="text-primary">▸ questions</span>{" "}
                  <span className="text-foreground">10 generated</span>
                </div>
                <div>
                  <span className="text-primary">▸ setup_steps</span>{" "}
                  <span className="text-foreground">7 steps</span>
                </div>
                <div className="h-1 rounded bg-muted overflow-hidden relative">
                  <div className="absolute inset-0 animate-shimmer" />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
